package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ChiharuPkPagosId generated by hbm2java
 */
public class ChiharuPkPagosId  implements java.io.Serializable {


     private String cedula;
     private BigDecimal valor;
     private String fecha;

    public ChiharuPkPagosId() {
    }

    public ChiharuPkPagosId(String cedula, BigDecimal valor, String fecha) {
       this.cedula = cedula;
       this.valor = valor;
       this.fecha = fecha;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChiharuPkPagosId) ) return false;
		 ChiharuPkPagosId castOther = ( ChiharuPkPagosId ) other; 
         
		 return ( (this.getCedula()==castOther.getCedula()) || ( this.getCedula()!=null && castOther.getCedula()!=null && this.getCedula().equals(castOther.getCedula()) ) )
 && ( (this.getValor()==castOther.getValor()) || ( this.getValor()!=null && castOther.getValor()!=null && this.getValor().equals(castOther.getValor()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCedula() == null ? 0 : this.getCedula().hashCode() );
         result = 37 * result + ( getValor() == null ? 0 : this.getValor().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


