package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1



/**
 * ChiharuPkPagos generated by hbm2java
 */
public class ChiharuPkPagos  implements java.io.Serializable {


     private ChiharuPkPagosId id;

    public ChiharuPkPagos() {
    }

    public ChiharuPkPagos(ChiharuPkPagosId id) {
       this.id = id;
    }
   
    public ChiharuPkPagosId getId() {
        return this.id;
    }
    
    public void setId(ChiharuPkPagosId id) {
        this.id = id;
    }




}


