package com.laticobsa.modelo;
// Generated 30-ago-2017 1:41:34 by Hibernate Tools 4.3.1



/**
 * LcAsignacioPiccaTmp generated by hbm2java
 */
public class LcAsignacioPiccaTmp  implements java.io.Serializable {


     private LcAsignacioPiccaTmpId id;

    public LcAsignacioPiccaTmp() {
    }

    public LcAsignacioPiccaTmp(LcAsignacioPiccaTmpId id) {
       this.id = id;
    }
   
    public LcAsignacioPiccaTmpId getId() {
        return this.id;
    }
    
    public void setId(LcAsignacioPiccaTmpId id) {
        this.id = id;
    }




}


