package com.laticobsa.modelo;
// Generated 22-jul-2017 13:48:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcClienteResultado generated by hbm2java
 */
public class LcClienteResultado  implements java.io.Serializable {


     private int idClienteResultado;
     private LcClientes lcClientes;
     private LcTipoResultado lcTipoResultado;
     private Date fechaRegistro;
     private String estado;

    public LcClienteResultado() {
    }

	
    public LcClienteResultado(int idClienteResultado) {
        this.idClienteResultado = idClienteResultado;
    }
    public LcClienteResultado(int idClienteResultado, LcClientes lcClientes, LcTipoResultado lcTipoResultado, Date fechaRegistro, String estado) {
       this.idClienteResultado = idClienteResultado;
       this.lcClientes = lcClientes;
       this.lcTipoResultado = lcTipoResultado;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
    }
   
    public int getIdClienteResultado() {
        return this.idClienteResultado;
    }
    
    public void setIdClienteResultado(int idClienteResultado) {
        this.idClienteResultado = idClienteResultado;
    }
    public LcClientes getLcClientes() {
        return this.lcClientes;
    }
    
    public void setLcClientes(LcClientes lcClientes) {
        this.lcClientes = lcClientes;
    }
    public LcTipoResultado getLcTipoResultado() {
        return this.lcTipoResultado;
    }
    
    public void setLcTipoResultado(LcTipoResultado lcTipoResultado) {
        this.lcTipoResultado = lcTipoResultado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


