package com.laticobsa.modelo;
// Generated 22-jul-2017 13:48:47 by Hibernate Tools 4.3.1



/**
 * LcCuotas2 generated by hbm2java
 */
public class LcCuotas2  implements java.io.Serializable {


     private LcCuotas2Id id;

    public LcCuotas2() {
    }

    public LcCuotas2(LcCuotas2Id id) {
       this.id = id;
    }
   
    public LcCuotas2Id getId() {
        return this.id;
    }
    
    public void setId(LcCuotas2Id id) {
        this.id = id;
    }




}


