package com.laticobsa.modelo;
// Generated 27-jun-2017 21:14:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LcCuotas2Id generated by hbm2java
 */
public class LcCuotas2Id  implements java.io.Serializable {


     private Integer idCuota;
     private Integer idArticulo;
     private Integer idCliente;
     private Integer numCuotas;
     private BigDecimal valorCuota;
     private BigDecimal interesCuota;
     private BigDecimal valorMora;
     private BigDecimal gastosCobranzas;
     private BigDecimal gastosAdicional;
     private BigDecimal otrosValores;
     private BigDecimal totalCuotas;
     private Date fechaPago;
     private Date fechaMaxPago;
     private Date fechaRegistro;
     private String estado;

    public LcCuotas2Id() {
    }

    public LcCuotas2Id(Integer idCuota, Integer idArticulo, Integer idCliente, Integer numCuotas, BigDecimal valorCuota, BigDecimal interesCuota, BigDecimal valorMora, BigDecimal gastosCobranzas, BigDecimal gastosAdicional, BigDecimal otrosValores, BigDecimal totalCuotas, Date fechaPago, Date fechaMaxPago, Date fechaRegistro, String estado) {
       this.idCuota = idCuota;
       this.idArticulo = idArticulo;
       this.idCliente = idCliente;
       this.numCuotas = numCuotas;
       this.valorCuota = valorCuota;
       this.interesCuota = interesCuota;
       this.valorMora = valorMora;
       this.gastosCobranzas = gastosCobranzas;
       this.gastosAdicional = gastosAdicional;
       this.otrosValores = otrosValores;
       this.totalCuotas = totalCuotas;
       this.fechaPago = fechaPago;
       this.fechaMaxPago = fechaMaxPago;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
    }
   
    public Integer getIdCuota() {
        return this.idCuota;
    }
    
    public void setIdCuota(Integer idCuota) {
        this.idCuota = idCuota;
    }
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getNumCuotas() {
        return this.numCuotas;
    }
    
    public void setNumCuotas(Integer numCuotas) {
        this.numCuotas = numCuotas;
    }
    public BigDecimal getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(BigDecimal valorCuota) {
        this.valorCuota = valorCuota;
    }
    public BigDecimal getInteresCuota() {
        return this.interesCuota;
    }
    
    public void setInteresCuota(BigDecimal interesCuota) {
        this.interesCuota = interesCuota;
    }
    public BigDecimal getValorMora() {
        return this.valorMora;
    }
    
    public void setValorMora(BigDecimal valorMora) {
        this.valorMora = valorMora;
    }
    public BigDecimal getGastosCobranzas() {
        return this.gastosCobranzas;
    }
    
    public void setGastosCobranzas(BigDecimal gastosCobranzas) {
        this.gastosCobranzas = gastosCobranzas;
    }
    public BigDecimal getGastosAdicional() {
        return this.gastosAdicional;
    }
    
    public void setGastosAdicional(BigDecimal gastosAdicional) {
        this.gastosAdicional = gastosAdicional;
    }
    public BigDecimal getOtrosValores() {
        return this.otrosValores;
    }
    
    public void setOtrosValores(BigDecimal otrosValores) {
        this.otrosValores = otrosValores;
    }
    public BigDecimal getTotalCuotas() {
        return this.totalCuotas;
    }
    
    public void setTotalCuotas(BigDecimal totalCuotas) {
        this.totalCuotas = totalCuotas;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public Date getFechaMaxPago() {
        return this.fechaMaxPago;
    }
    
    public void setFechaMaxPago(Date fechaMaxPago) {
        this.fechaMaxPago = fechaMaxPago;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LcCuotas2Id) ) return false;
		 LcCuotas2Id castOther = ( LcCuotas2Id ) other; 
         
		 return ( (this.getIdCuota()==castOther.getIdCuota()) || ( this.getIdCuota()!=null && castOther.getIdCuota()!=null && this.getIdCuota().equals(castOther.getIdCuota()) ) )
 && ( (this.getIdArticulo()==castOther.getIdArticulo()) || ( this.getIdArticulo()!=null && castOther.getIdArticulo()!=null && this.getIdArticulo().equals(castOther.getIdArticulo()) ) )
 && ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) )
 && ( (this.getNumCuotas()==castOther.getNumCuotas()) || ( this.getNumCuotas()!=null && castOther.getNumCuotas()!=null && this.getNumCuotas().equals(castOther.getNumCuotas()) ) )
 && ( (this.getValorCuota()==castOther.getValorCuota()) || ( this.getValorCuota()!=null && castOther.getValorCuota()!=null && this.getValorCuota().equals(castOther.getValorCuota()) ) )
 && ( (this.getInteresCuota()==castOther.getInteresCuota()) || ( this.getInteresCuota()!=null && castOther.getInteresCuota()!=null && this.getInteresCuota().equals(castOther.getInteresCuota()) ) )
 && ( (this.getValorMora()==castOther.getValorMora()) || ( this.getValorMora()!=null && castOther.getValorMora()!=null && this.getValorMora().equals(castOther.getValorMora()) ) )
 && ( (this.getGastosCobranzas()==castOther.getGastosCobranzas()) || ( this.getGastosCobranzas()!=null && castOther.getGastosCobranzas()!=null && this.getGastosCobranzas().equals(castOther.getGastosCobranzas()) ) )
 && ( (this.getGastosAdicional()==castOther.getGastosAdicional()) || ( this.getGastosAdicional()!=null && castOther.getGastosAdicional()!=null && this.getGastosAdicional().equals(castOther.getGastosAdicional()) ) )
 && ( (this.getOtrosValores()==castOther.getOtrosValores()) || ( this.getOtrosValores()!=null && castOther.getOtrosValores()!=null && this.getOtrosValores().equals(castOther.getOtrosValores()) ) )
 && ( (this.getTotalCuotas()==castOther.getTotalCuotas()) || ( this.getTotalCuotas()!=null && castOther.getTotalCuotas()!=null && this.getTotalCuotas().equals(castOther.getTotalCuotas()) ) )
 && ( (this.getFechaPago()==castOther.getFechaPago()) || ( this.getFechaPago()!=null && castOther.getFechaPago()!=null && this.getFechaPago().equals(castOther.getFechaPago()) ) )
 && ( (this.getFechaMaxPago()==castOther.getFechaMaxPago()) || ( this.getFechaMaxPago()!=null && castOther.getFechaMaxPago()!=null && this.getFechaMaxPago().equals(castOther.getFechaMaxPago()) ) )
 && ( (this.getFechaRegistro()==castOther.getFechaRegistro()) || ( this.getFechaRegistro()!=null && castOther.getFechaRegistro()!=null && this.getFechaRegistro().equals(castOther.getFechaRegistro()) ) )
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCuota() == null ? 0 : this.getIdCuota().hashCode() );
         result = 37 * result + ( getIdArticulo() == null ? 0 : this.getIdArticulo().hashCode() );
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         result = 37 * result + ( getNumCuotas() == null ? 0 : this.getNumCuotas().hashCode() );
         result = 37 * result + ( getValorCuota() == null ? 0 : this.getValorCuota().hashCode() );
         result = 37 * result + ( getInteresCuota() == null ? 0 : this.getInteresCuota().hashCode() );
         result = 37 * result + ( getValorMora() == null ? 0 : this.getValorMora().hashCode() );
         result = 37 * result + ( getGastosCobranzas() == null ? 0 : this.getGastosCobranzas().hashCode() );
         result = 37 * result + ( getGastosAdicional() == null ? 0 : this.getGastosAdicional().hashCode() );
         result = 37 * result + ( getOtrosValores() == null ? 0 : this.getOtrosValores().hashCode() );
         result = 37 * result + ( getTotalCuotas() == null ? 0 : this.getTotalCuotas().hashCode() );
         result = 37 * result + ( getFechaPago() == null ? 0 : this.getFechaPago().hashCode() );
         result = 37 * result + ( getFechaMaxPago() == null ? 0 : this.getFechaMaxPago().hashCode() );
         result = 37 * result + ( getFechaRegistro() == null ? 0 : this.getFechaRegistro().hashCode() );
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         return result;
   }   


}


