package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1



/**
 * LcDatosDeudores2 generated by hbm2java
 */
public class LcDatosDeudores2  implements java.io.Serializable {


     private LcDatosDeudores2Id id;

    public LcDatosDeudores2() {
    }

    public LcDatosDeudores2(LcDatosDeudores2Id id) {
       this.id = id;
    }
   
    public LcDatosDeudores2Id getId() {
        return this.id;
    }
    
    public void setId(LcDatosDeudores2Id id) {
        this.id = id;
    }




}


