package com.laticobsa.modelo;
// Generated 27-jun-2017 21:14:43 by Hibernate Tools 4.3.1



/**
 * LcDatosDeudores3 generated by hbm2java
 */
public class LcDatosDeudores3  implements java.io.Serializable {


     private LcDatosDeudores3Id id;

    public LcDatosDeudores3() {
    }

    public LcDatosDeudores3(LcDatosDeudores3Id id) {
       this.id = id;
    }
   
    public LcDatosDeudores3Id getId() {
        return this.id;
    }
    
    public void setId(LcDatosDeudores3Id id) {
        this.id = id;
    }




}


