package com.laticobsa.modelo;
// Generated 27-jun-2017 21:14:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LcDetCampanias generated by hbm2java
 */
public class LcDetCampanias  implements java.io.Serializable {


     private int idDetCampania;
     private Integer idEmpresa;
     private Integer idAgencia;
     private Integer idCliente;
     private Integer tipoIdentioficacion;
     private String identificacion;
     private String nombres;
     private String apellidos;
     private BigDecimal montoAsignado;
     private BigDecimal interesMora;
     private BigDecimal interesCuota;
     private BigDecimal interesCapital;
     private BigDecimal interesAdicional;
     private BigDecimal interesOtros;
     private BigDecimal totalVencido;
     private Date fechaCreacion;
     private String estado;

    public LcDetCampanias() {
    }

	
    public LcDetCampanias(int idDetCampania) {
        this.idDetCampania = idDetCampania;
    }
    public LcDetCampanias(int idDetCampania, Integer idEmpresa, Integer idAgencia, Integer idCliente, Integer tipoIdentioficacion, String identificacion, String nombres, String apellidos, BigDecimal montoAsignado, BigDecimal interesMora, BigDecimal interesCuota, BigDecimal interesCapital, BigDecimal interesAdicional, BigDecimal interesOtros, BigDecimal totalVencido, Date fechaCreacion, String estado) {
       this.idDetCampania = idDetCampania;
       this.idEmpresa = idEmpresa;
       this.idAgencia = idAgencia;
       this.idCliente = idCliente;
       this.tipoIdentioficacion = tipoIdentioficacion;
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.montoAsignado = montoAsignado;
       this.interesMora = interesMora;
       this.interesCuota = interesCuota;
       this.interesCapital = interesCapital;
       this.interesAdicional = interesAdicional;
       this.interesOtros = interesOtros;
       this.totalVencido = totalVencido;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
    public int getIdDetCampania() {
        return this.idDetCampania;
    }
    
    public void setIdDetCampania(int idDetCampania) {
        this.idDetCampania = idDetCampania;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Integer getIdAgencia() {
        return this.idAgencia;
    }
    
    public void setIdAgencia(Integer idAgencia) {
        this.idAgencia = idAgencia;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getTipoIdentioficacion() {
        return this.tipoIdentioficacion;
    }
    
    public void setTipoIdentioficacion(Integer tipoIdentioficacion) {
        this.tipoIdentioficacion = tipoIdentioficacion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public BigDecimal getMontoAsignado() {
        return this.montoAsignado;
    }
    
    public void setMontoAsignado(BigDecimal montoAsignado) {
        this.montoAsignado = montoAsignado;
    }
    public BigDecimal getInteresMora() {
        return this.interesMora;
    }
    
    public void setInteresMora(BigDecimal interesMora) {
        this.interesMora = interesMora;
    }
    public BigDecimal getInteresCuota() {
        return this.interesCuota;
    }
    
    public void setInteresCuota(BigDecimal interesCuota) {
        this.interesCuota = interesCuota;
    }
    public BigDecimal getInteresCapital() {
        return this.interesCapital;
    }
    
    public void setInteresCapital(BigDecimal interesCapital) {
        this.interesCapital = interesCapital;
    }
    public BigDecimal getInteresAdicional() {
        return this.interesAdicional;
    }
    
    public void setInteresAdicional(BigDecimal interesAdicional) {
        this.interesAdicional = interesAdicional;
    }
    public BigDecimal getInteresOtros() {
        return this.interesOtros;
    }
    
    public void setInteresOtros(BigDecimal interesOtros) {
        this.interesOtros = interesOtros;
    }
    public BigDecimal getTotalVencido() {
        return this.totalVencido;
    }
    
    public void setTotalVencido(BigDecimal totalVencido) {
        this.totalVencido = totalVencido;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


