package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1



/**
 * LcGestiones4 generated by hbm2java
 */
public class LcGestiones4  implements java.io.Serializable {


     private LcGestiones4Id id;

    public LcGestiones4() {
    }

    public LcGestiones4(LcGestiones4Id id) {
       this.id = id;
    }
   
    public LcGestiones4Id getId() {
        return this.id;
    }
    
    public void setId(LcGestiones4Id id) {
        this.id = id;
    }




}


