package com.laticobsa.modelo;
// Generated 22-jul-2017 13:48:47 by Hibernate Tools 4.3.1



/**
 * LcGestiones2 generated by hbm2java
 */
public class LcGestiones2  implements java.io.Serializable {


     private LcGestiones2Id id;

    public LcGestiones2() {
    }

    public LcGestiones2(LcGestiones2Id id) {
       this.id = id;
    }
   
    public LcGestiones2Id getId() {
        return this.id;
    }
    
    public void setId(LcGestiones2Id id) {
        this.id = id;
    }




}


