package com.laticobsa.modelo;
// Generated 30-ago-2017 1:41:34 by Hibernate Tools 4.3.1



/**
 * LcGestiones3 generated by hbm2java
 */
public class LcGestiones3  implements java.io.Serializable {


     private LcGestiones3Id id;

    public LcGestiones3() {
    }

    public LcGestiones3(LcGestiones3Id id) {
       this.id = id;
    }
   
    public LcGestiones3Id getId() {
        return this.id;
    }
    
    public void setId(LcGestiones3Id id) {
        this.id = id;
    }




}


