package com.laticobsa.modelo;
// Generated 30-ago-2017 1:41:34 by Hibernate Tools 4.3.1



/**
 * LcParroquias generated by hbm2java
 */
public class LcParroquias  implements java.io.Serializable {


     private int idParroquia;
     private LcCiudad lcCiudad;
     private String parroquia;
     private String estado;

    public LcParroquias() {
    }

	
    public LcParroquias(int idParroquia) {
        this.idParroquia = idParroquia;
    }
    public LcParroquias(int idParroquia, LcCiudad lcCiudad, String parroquia, String estado) {
       this.idParroquia = idParroquia;
       this.lcCiudad = lcCiudad;
       this.parroquia = parroquia;
       this.estado = estado;
    }
   
    public int getIdParroquia() {
        return this.idParroquia;
    }
    
    public void setIdParroquia(int idParroquia) {
        this.idParroquia = idParroquia;
    }
    public LcCiudad getLcCiudad() {
        return this.lcCiudad;
    }
    
    public void setLcCiudad(LcCiudad lcCiudad) {
        this.lcCiudad = lcCiudad;
    }
    public String getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(String parroquia) {
        this.parroquia = parroquia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


