package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1



/**
 * LcPiccaTmp generated by hbm2java
 */
public class LcPiccaTmp  implements java.io.Serializable {


     private LcPiccaTmpId id;

    public LcPiccaTmp() {
    }

    public LcPiccaTmp(LcPiccaTmpId id) {
       this.id = id;
    }
   
    public LcPiccaTmpId getId() {
        return this.id;
    }
    
    public void setId(LcPiccaTmpId id) {
        this.id = id;
    }




}


