package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcTipoResultado generated by hbm2java
 */
public class LcTipoResultado  implements java.io.Serializable {


     private int idTipoResultado;
     private LcTipoGestion lcTipoGestion;
     private String nombreTipoResultado;
     private String observacion;
     private Date fechaRegistro;
     private String estado;
     private Set lcGestioneses = new HashSet(0);

    public LcTipoResultado() {
    }

	
    public LcTipoResultado(int idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public LcTipoResultado(int idTipoResultado, LcTipoGestion lcTipoGestion, String nombreTipoResultado, String observacion, Date fechaRegistro, String estado, Set lcGestioneses) {
       this.idTipoResultado = idTipoResultado;
       this.lcTipoGestion = lcTipoGestion;
       this.nombreTipoResultado = nombreTipoResultado;
       this.observacion = observacion;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.lcGestioneses = lcGestioneses;
    }
   
    public int getIdTipoResultado() {
        return this.idTipoResultado;
    }
    
    public void setIdTipoResultado(int idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public LcTipoGestion getLcTipoGestion() {
        return this.lcTipoGestion;
    }
    
    public void setLcTipoGestion(LcTipoGestion lcTipoGestion) {
        this.lcTipoGestion = lcTipoGestion;
    }
    public String getNombreTipoResultado() {
        return this.nombreTipoResultado;
    }
    
    public void setNombreTipoResultado(String nombreTipoResultado) {
        this.nombreTipoResultado = nombreTipoResultado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcGestioneses() {
        return this.lcGestioneses;
    }
    
    public void setLcGestioneses(Set lcGestioneses) {
        this.lcGestioneses = lcGestioneses;
    }




}


