package com.laticobsa.modelo;
// Generated 27-jun-2017 21:14:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcTransaccionesHist generated by hbm2java
 */
public class LcTransaccionesHist  implements java.io.Serializable {


     private int idTransaccion;
     private Integer idDeudor;
     private Integer idCartera;
     private Integer idEmpleado;
     private Integer idTipoGestion;
     private Integer idTipoResultado;
     private String observacion;
     private Date fechaTransaccion;
     private String estado;

    public LcTransaccionesHist() {
    }

	
    public LcTransaccionesHist(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public LcTransaccionesHist(int idTransaccion, Integer idDeudor, Integer idCartera, Integer idEmpleado, Integer idTipoGestion, Integer idTipoResultado, String observacion, Date fechaTransaccion, String estado) {
       this.idTransaccion = idTransaccion;
       this.idDeudor = idDeudor;
       this.idCartera = idCartera;
       this.idEmpleado = idEmpleado;
       this.idTipoGestion = idTipoGestion;
       this.idTipoResultado = idTipoResultado;
       this.observacion = observacion;
       this.fechaTransaccion = fechaTransaccion;
       this.estado = estado;
    }
   
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Integer getIdDeudor() {
        return this.idDeudor;
    }
    
    public void setIdDeudor(Integer idDeudor) {
        this.idDeudor = idDeudor;
    }
    public Integer getIdCartera() {
        return this.idCartera;
    }
    
    public void setIdCartera(Integer idCartera) {
        this.idCartera = idCartera;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Integer getIdTipoGestion() {
        return this.idTipoGestion;
    }
    
    public void setIdTipoGestion(Integer idTipoGestion) {
        this.idTipoGestion = idTipoGestion;
    }
    public Integer getIdTipoResultado() {
        return this.idTipoResultado;
    }
    
    public void setIdTipoResultado(Integer idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


