package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LcTransacciones2Id generated by hbm2java
 */
public class LcTransacciones2Id  implements java.io.Serializable {


     private Integer idTransaccion;
     private Integer idDeudor;
     private Integer idCliente;
     private Integer idEmpleado;
     private Integer idTipoIdentificacion;
     private String identificacion;
     private BigDecimal montoAsignado;
     private BigDecimal ultimoPago;
     private Integer numeroPagos;
     private BigDecimal valorCuota;
     private Integer diasMora;
     private BigDecimal interesMora;
     private BigDecimal interesCapital;
     private BigDecimal interesAdicional;
     private BigDecimal interesOtros;
     private Integer diasVencidos;
     private BigDecimal totalVencidos;
     private Date fechaTransaccion;
     private String estado;
     private String descripcionCarga;
     private String numCuenta;

    public LcTransacciones2Id() {
    }

    public LcTransacciones2Id(Integer idTransaccion, Integer idDeudor, Integer idCliente, Integer idEmpleado, Integer idTipoIdentificacion, String identificacion, BigDecimal montoAsignado, BigDecimal ultimoPago, Integer numeroPagos, BigDecimal valorCuota, Integer diasMora, BigDecimal interesMora, BigDecimal interesCapital, BigDecimal interesAdicional, BigDecimal interesOtros, Integer diasVencidos, BigDecimal totalVencidos, Date fechaTransaccion, String estado, String descripcionCarga, String numCuenta) {
       this.idTransaccion = idTransaccion;
       this.idDeudor = idDeudor;
       this.idCliente = idCliente;
       this.idEmpleado = idEmpleado;
       this.idTipoIdentificacion = idTipoIdentificacion;
       this.identificacion = identificacion;
       this.montoAsignado = montoAsignado;
       this.ultimoPago = ultimoPago;
       this.numeroPagos = numeroPagos;
       this.valorCuota = valorCuota;
       this.diasMora = diasMora;
       this.interesMora = interesMora;
       this.interesCapital = interesCapital;
       this.interesAdicional = interesAdicional;
       this.interesOtros = interesOtros;
       this.diasVencidos = diasVencidos;
       this.totalVencidos = totalVencidos;
       this.fechaTransaccion = fechaTransaccion;
       this.estado = estado;
       this.descripcionCarga = descripcionCarga;
       this.numCuenta = numCuenta;
    }
   
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public Integer getIdDeudor() {
        return this.idDeudor;
    }
    
    public void setIdDeudor(Integer idDeudor) {
        this.idDeudor = idDeudor;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Integer getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(Integer idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public BigDecimal getMontoAsignado() {
        return this.montoAsignado;
    }
    
    public void setMontoAsignado(BigDecimal montoAsignado) {
        this.montoAsignado = montoAsignado;
    }
    public BigDecimal getUltimoPago() {
        return this.ultimoPago;
    }
    
    public void setUltimoPago(BigDecimal ultimoPago) {
        this.ultimoPago = ultimoPago;
    }
    public Integer getNumeroPagos() {
        return this.numeroPagos;
    }
    
    public void setNumeroPagos(Integer numeroPagos) {
        this.numeroPagos = numeroPagos;
    }
    public BigDecimal getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(BigDecimal valorCuota) {
        this.valorCuota = valorCuota;
    }
    public Integer getDiasMora() {
        return this.diasMora;
    }
    
    public void setDiasMora(Integer diasMora) {
        this.diasMora = diasMora;
    }
    public BigDecimal getInteresMora() {
        return this.interesMora;
    }
    
    public void setInteresMora(BigDecimal interesMora) {
        this.interesMora = interesMora;
    }
    public BigDecimal getInteresCapital() {
        return this.interesCapital;
    }
    
    public void setInteresCapital(BigDecimal interesCapital) {
        this.interesCapital = interesCapital;
    }
    public BigDecimal getInteresAdicional() {
        return this.interesAdicional;
    }
    
    public void setInteresAdicional(BigDecimal interesAdicional) {
        this.interesAdicional = interesAdicional;
    }
    public BigDecimal getInteresOtros() {
        return this.interesOtros;
    }
    
    public void setInteresOtros(BigDecimal interesOtros) {
        this.interesOtros = interesOtros;
    }
    public Integer getDiasVencidos() {
        return this.diasVencidos;
    }
    
    public void setDiasVencidos(Integer diasVencidos) {
        this.diasVencidos = diasVencidos;
    }
    public BigDecimal getTotalVencidos() {
        return this.totalVencidos;
    }
    
    public void setTotalVencidos(BigDecimal totalVencidos) {
        this.totalVencidos = totalVencidos;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcionCarga() {
        return this.descripcionCarga;
    }
    
    public void setDescripcionCarga(String descripcionCarga) {
        this.descripcionCarga = descripcionCarga;
    }
    public String getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(String numCuenta) {
        this.numCuenta = numCuenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LcTransacciones2Id) ) return false;
		 LcTransacciones2Id castOther = ( LcTransacciones2Id ) other; 
         
		 return ( (this.getIdTransaccion()==castOther.getIdTransaccion()) || ( this.getIdTransaccion()!=null && castOther.getIdTransaccion()!=null && this.getIdTransaccion().equals(castOther.getIdTransaccion()) ) )
 && ( (this.getIdDeudor()==castOther.getIdDeudor()) || ( this.getIdDeudor()!=null && castOther.getIdDeudor()!=null && this.getIdDeudor().equals(castOther.getIdDeudor()) ) )
 && ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) )
 && ( (this.getIdEmpleado()==castOther.getIdEmpleado()) || ( this.getIdEmpleado()!=null && castOther.getIdEmpleado()!=null && this.getIdEmpleado().equals(castOther.getIdEmpleado()) ) )
 && ( (this.getIdTipoIdentificacion()==castOther.getIdTipoIdentificacion()) || ( this.getIdTipoIdentificacion()!=null && castOther.getIdTipoIdentificacion()!=null && this.getIdTipoIdentificacion().equals(castOther.getIdTipoIdentificacion()) ) )
 && ( (this.getIdentificacion()==castOther.getIdentificacion()) || ( this.getIdentificacion()!=null && castOther.getIdentificacion()!=null && this.getIdentificacion().equals(castOther.getIdentificacion()) ) )
 && ( (this.getMontoAsignado()==castOther.getMontoAsignado()) || ( this.getMontoAsignado()!=null && castOther.getMontoAsignado()!=null && this.getMontoAsignado().equals(castOther.getMontoAsignado()) ) )
 && ( (this.getUltimoPago()==castOther.getUltimoPago()) || ( this.getUltimoPago()!=null && castOther.getUltimoPago()!=null && this.getUltimoPago().equals(castOther.getUltimoPago()) ) )
 && ( (this.getNumeroPagos()==castOther.getNumeroPagos()) || ( this.getNumeroPagos()!=null && castOther.getNumeroPagos()!=null && this.getNumeroPagos().equals(castOther.getNumeroPagos()) ) )
 && ( (this.getValorCuota()==castOther.getValorCuota()) || ( this.getValorCuota()!=null && castOther.getValorCuota()!=null && this.getValorCuota().equals(castOther.getValorCuota()) ) )
 && ( (this.getDiasMora()==castOther.getDiasMora()) || ( this.getDiasMora()!=null && castOther.getDiasMora()!=null && this.getDiasMora().equals(castOther.getDiasMora()) ) )
 && ( (this.getInteresMora()==castOther.getInteresMora()) || ( this.getInteresMora()!=null && castOther.getInteresMora()!=null && this.getInteresMora().equals(castOther.getInteresMora()) ) )
 && ( (this.getInteresCapital()==castOther.getInteresCapital()) || ( this.getInteresCapital()!=null && castOther.getInteresCapital()!=null && this.getInteresCapital().equals(castOther.getInteresCapital()) ) )
 && ( (this.getInteresAdicional()==castOther.getInteresAdicional()) || ( this.getInteresAdicional()!=null && castOther.getInteresAdicional()!=null && this.getInteresAdicional().equals(castOther.getInteresAdicional()) ) )
 && ( (this.getInteresOtros()==castOther.getInteresOtros()) || ( this.getInteresOtros()!=null && castOther.getInteresOtros()!=null && this.getInteresOtros().equals(castOther.getInteresOtros()) ) )
 && ( (this.getDiasVencidos()==castOther.getDiasVencidos()) || ( this.getDiasVencidos()!=null && castOther.getDiasVencidos()!=null && this.getDiasVencidos().equals(castOther.getDiasVencidos()) ) )
 && ( (this.getTotalVencidos()==castOther.getTotalVencidos()) || ( this.getTotalVencidos()!=null && castOther.getTotalVencidos()!=null && this.getTotalVencidos().equals(castOther.getTotalVencidos()) ) )
 && ( (this.getFechaTransaccion()==castOther.getFechaTransaccion()) || ( this.getFechaTransaccion()!=null && castOther.getFechaTransaccion()!=null && this.getFechaTransaccion().equals(castOther.getFechaTransaccion()) ) )
 && ( (this.getEstado()==castOther.getEstado()) || ( this.getEstado()!=null && castOther.getEstado()!=null && this.getEstado().equals(castOther.getEstado()) ) )
 && ( (this.getDescripcionCarga()==castOther.getDescripcionCarga()) || ( this.getDescripcionCarga()!=null && castOther.getDescripcionCarga()!=null && this.getDescripcionCarga().equals(castOther.getDescripcionCarga()) ) )
 && ( (this.getNumCuenta()==castOther.getNumCuenta()) || ( this.getNumCuenta()!=null && castOther.getNumCuenta()!=null && this.getNumCuenta().equals(castOther.getNumCuenta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTransaccion() == null ? 0 : this.getIdTransaccion().hashCode() );
         result = 37 * result + ( getIdDeudor() == null ? 0 : this.getIdDeudor().hashCode() );
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         result = 37 * result + ( getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode() );
         result = 37 * result + ( getIdTipoIdentificacion() == null ? 0 : this.getIdTipoIdentificacion().hashCode() );
         result = 37 * result + ( getIdentificacion() == null ? 0 : this.getIdentificacion().hashCode() );
         result = 37 * result + ( getMontoAsignado() == null ? 0 : this.getMontoAsignado().hashCode() );
         result = 37 * result + ( getUltimoPago() == null ? 0 : this.getUltimoPago().hashCode() );
         result = 37 * result + ( getNumeroPagos() == null ? 0 : this.getNumeroPagos().hashCode() );
         result = 37 * result + ( getValorCuota() == null ? 0 : this.getValorCuota().hashCode() );
         result = 37 * result + ( getDiasMora() == null ? 0 : this.getDiasMora().hashCode() );
         result = 37 * result + ( getInteresMora() == null ? 0 : this.getInteresMora().hashCode() );
         result = 37 * result + ( getInteresCapital() == null ? 0 : this.getInteresCapital().hashCode() );
         result = 37 * result + ( getInteresAdicional() == null ? 0 : this.getInteresAdicional().hashCode() );
         result = 37 * result + ( getInteresOtros() == null ? 0 : this.getInteresOtros().hashCode() );
         result = 37 * result + ( getDiasVencidos() == null ? 0 : this.getDiasVencidos().hashCode() );
         result = 37 * result + ( getTotalVencidos() == null ? 0 : this.getTotalVencidos().hashCode() );
         result = 37 * result + ( getFechaTransaccion() == null ? 0 : this.getFechaTransaccion().hashCode() );
         result = 37 * result + ( getEstado() == null ? 0 : this.getEstado().hashCode() );
         result = 37 * result + ( getDescripcionCarga() == null ? 0 : this.getDescripcionCarga().hashCode() );
         result = 37 * result + ( getNumCuenta() == null ? 0 : this.getNumCuenta().hashCode() );
         return result;
   }   


}


