package com.laticobsa.modelo;
// Generated 27-jun-2017 21:14:43 by Hibernate Tools 4.3.1



/**
 * LcTransacciones2 generated by hbm2java
 */
public class LcTransacciones2  implements java.io.Serializable {


     private LcTransacciones2Id id;

    public LcTransacciones2() {
    }

    public LcTransacciones2(LcTransacciones2Id id) {
       this.id = id;
    }
   
    public LcTransacciones2Id getId() {
        return this.id;
    }
    
    public void setId(LcTransacciones2Id id) {
        this.id = id;
    }




}


