package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1



/**
 * LloacanaPyccaOficiales generated by hbm2java
 */
public class LloacanaPyccaOficiales  implements java.io.Serializable {


     private LloacanaPyccaOficialesId id;

    public LloacanaPyccaOficiales() {
    }

    public LloacanaPyccaOficiales(LloacanaPyccaOficialesId id) {
       this.id = id;
    }
   
    public LloacanaPyccaOficialesId getId() {
        return this.id;
    }
    
    public void setId(LloacanaPyccaOficialesId id) {
        this.id = id;
    }




}


