package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1



/**
 * LloacanaPyccaPagos generated by hbm2java
 */
public class LloacanaPyccaPagos  implements java.io.Serializable {


     private LloacanaPyccaPagosId id;

    public LloacanaPyccaPagos() {
    }

    public LloacanaPyccaPagos(LloacanaPyccaPagosId id) {
       this.id = id;
    }
   
    public LloacanaPyccaPagosId getId() {
        return this.id;
    }
    
    public void setId(LloacanaPyccaPagosId id) {
        this.id = id;
    }




}


