package com.laticobsa.modelo;
// Generated 09-jul-2017 23:23:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LloacanaPyccaPagosId generated by hbm2java
 */
public class LloacanaPyccaPagosId  implements java.io.Serializable {


     private String camp1;
     private String camp2;
     private String camp3;
     private String camp4;
     private String camp5;
     private String camp6;
     private String camp7;
     private String camp8;
     private BigDecimal camp9;
     private String camp10;
     private String camp11;
     private String camp12;
     private String camp13;
     private String camp14;
     private String camp15;
     private String camp16;
     private String camp17;

    public LloacanaPyccaPagosId() {
    }

    public LloacanaPyccaPagosId(String camp1, String camp2, String camp3, String camp4, String camp5, String camp6, String camp7, String camp8, BigDecimal camp9, String camp10, String camp11, String camp12, String camp13, String camp14, String camp15, String camp16, String camp17) {
       this.camp1 = camp1;
       this.camp2 = camp2;
       this.camp3 = camp3;
       this.camp4 = camp4;
       this.camp5 = camp5;
       this.camp6 = camp6;
       this.camp7 = camp7;
       this.camp8 = camp8;
       this.camp9 = camp9;
       this.camp10 = camp10;
       this.camp11 = camp11;
       this.camp12 = camp12;
       this.camp13 = camp13;
       this.camp14 = camp14;
       this.camp15 = camp15;
       this.camp16 = camp16;
       this.camp17 = camp17;
    }
   
    public String getCamp1() {
        return this.camp1;
    }
    
    public void setCamp1(String camp1) {
        this.camp1 = camp1;
    }
    public String getCamp2() {
        return this.camp2;
    }
    
    public void setCamp2(String camp2) {
        this.camp2 = camp2;
    }
    public String getCamp3() {
        return this.camp3;
    }
    
    public void setCamp3(String camp3) {
        this.camp3 = camp3;
    }
    public String getCamp4() {
        return this.camp4;
    }
    
    public void setCamp4(String camp4) {
        this.camp4 = camp4;
    }
    public String getCamp5() {
        return this.camp5;
    }
    
    public void setCamp5(String camp5) {
        this.camp5 = camp5;
    }
    public String getCamp6() {
        return this.camp6;
    }
    
    public void setCamp6(String camp6) {
        this.camp6 = camp6;
    }
    public String getCamp7() {
        return this.camp7;
    }
    
    public void setCamp7(String camp7) {
        this.camp7 = camp7;
    }
    public String getCamp8() {
        return this.camp8;
    }
    
    public void setCamp8(String camp8) {
        this.camp8 = camp8;
    }
    public BigDecimal getCamp9() {
        return this.camp9;
    }
    
    public void setCamp9(BigDecimal camp9) {
        this.camp9 = camp9;
    }
    public String getCamp10() {
        return this.camp10;
    }
    
    public void setCamp10(String camp10) {
        this.camp10 = camp10;
    }
    public String getCamp11() {
        return this.camp11;
    }
    
    public void setCamp11(String camp11) {
        this.camp11 = camp11;
    }
    public String getCamp12() {
        return this.camp12;
    }
    
    public void setCamp12(String camp12) {
        this.camp12 = camp12;
    }
    public String getCamp13() {
        return this.camp13;
    }
    
    public void setCamp13(String camp13) {
        this.camp13 = camp13;
    }
    public String getCamp14() {
        return this.camp14;
    }
    
    public void setCamp14(String camp14) {
        this.camp14 = camp14;
    }
    public String getCamp15() {
        return this.camp15;
    }
    
    public void setCamp15(String camp15) {
        this.camp15 = camp15;
    }
    public String getCamp16() {
        return this.camp16;
    }
    
    public void setCamp16(String camp16) {
        this.camp16 = camp16;
    }
    public String getCamp17() {
        return this.camp17;
    }
    
    public void setCamp17(String camp17) {
        this.camp17 = camp17;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LloacanaPyccaPagosId) ) return false;
		 LloacanaPyccaPagosId castOther = ( LloacanaPyccaPagosId ) other; 
         
		 return ( (this.getCamp1()==castOther.getCamp1()) || ( this.getCamp1()!=null && castOther.getCamp1()!=null && this.getCamp1().equals(castOther.getCamp1()) ) )
 && ( (this.getCamp2()==castOther.getCamp2()) || ( this.getCamp2()!=null && castOther.getCamp2()!=null && this.getCamp2().equals(castOther.getCamp2()) ) )
 && ( (this.getCamp3()==castOther.getCamp3()) || ( this.getCamp3()!=null && castOther.getCamp3()!=null && this.getCamp3().equals(castOther.getCamp3()) ) )
 && ( (this.getCamp4()==castOther.getCamp4()) || ( this.getCamp4()!=null && castOther.getCamp4()!=null && this.getCamp4().equals(castOther.getCamp4()) ) )
 && ( (this.getCamp5()==castOther.getCamp5()) || ( this.getCamp5()!=null && castOther.getCamp5()!=null && this.getCamp5().equals(castOther.getCamp5()) ) )
 && ( (this.getCamp6()==castOther.getCamp6()) || ( this.getCamp6()!=null && castOther.getCamp6()!=null && this.getCamp6().equals(castOther.getCamp6()) ) )
 && ( (this.getCamp7()==castOther.getCamp7()) || ( this.getCamp7()!=null && castOther.getCamp7()!=null && this.getCamp7().equals(castOther.getCamp7()) ) )
 && ( (this.getCamp8()==castOther.getCamp8()) || ( this.getCamp8()!=null && castOther.getCamp8()!=null && this.getCamp8().equals(castOther.getCamp8()) ) )
 && ( (this.getCamp9()==castOther.getCamp9()) || ( this.getCamp9()!=null && castOther.getCamp9()!=null && this.getCamp9().equals(castOther.getCamp9()) ) )
 && ( (this.getCamp10()==castOther.getCamp10()) || ( this.getCamp10()!=null && castOther.getCamp10()!=null && this.getCamp10().equals(castOther.getCamp10()) ) )
 && ( (this.getCamp11()==castOther.getCamp11()) || ( this.getCamp11()!=null && castOther.getCamp11()!=null && this.getCamp11().equals(castOther.getCamp11()) ) )
 && ( (this.getCamp12()==castOther.getCamp12()) || ( this.getCamp12()!=null && castOther.getCamp12()!=null && this.getCamp12().equals(castOther.getCamp12()) ) )
 && ( (this.getCamp13()==castOther.getCamp13()) || ( this.getCamp13()!=null && castOther.getCamp13()!=null && this.getCamp13().equals(castOther.getCamp13()) ) )
 && ( (this.getCamp14()==castOther.getCamp14()) || ( this.getCamp14()!=null && castOther.getCamp14()!=null && this.getCamp14().equals(castOther.getCamp14()) ) )
 && ( (this.getCamp15()==castOther.getCamp15()) || ( this.getCamp15()!=null && castOther.getCamp15()!=null && this.getCamp15().equals(castOther.getCamp15()) ) )
 && ( (this.getCamp16()==castOther.getCamp16()) || ( this.getCamp16()!=null && castOther.getCamp16()!=null && this.getCamp16().equals(castOther.getCamp16()) ) )
 && ( (this.getCamp17()==castOther.getCamp17()) || ( this.getCamp17()!=null && castOther.getCamp17()!=null && this.getCamp17().equals(castOther.getCamp17()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCamp1() == null ? 0 : this.getCamp1().hashCode() );
         result = 37 * result + ( getCamp2() == null ? 0 : this.getCamp2().hashCode() );
         result = 37 * result + ( getCamp3() == null ? 0 : this.getCamp3().hashCode() );
         result = 37 * result + ( getCamp4() == null ? 0 : this.getCamp4().hashCode() );
         result = 37 * result + ( getCamp5() == null ? 0 : this.getCamp5().hashCode() );
         result = 37 * result + ( getCamp6() == null ? 0 : this.getCamp6().hashCode() );
         result = 37 * result + ( getCamp7() == null ? 0 : this.getCamp7().hashCode() );
         result = 37 * result + ( getCamp8() == null ? 0 : this.getCamp8().hashCode() );
         result = 37 * result + ( getCamp9() == null ? 0 : this.getCamp9().hashCode() );
         result = 37 * result + ( getCamp10() == null ? 0 : this.getCamp10().hashCode() );
         result = 37 * result + ( getCamp11() == null ? 0 : this.getCamp11().hashCode() );
         result = 37 * result + ( getCamp12() == null ? 0 : this.getCamp12().hashCode() );
         result = 37 * result + ( getCamp13() == null ? 0 : this.getCamp13().hashCode() );
         result = 37 * result + ( getCamp14() == null ? 0 : this.getCamp14().hashCode() );
         result = 37 * result + ( getCamp15() == null ? 0 : this.getCamp15().hashCode() );
         result = 37 * result + ( getCamp16() == null ? 0 : this.getCamp16().hashCode() );
         result = 37 * result + ( getCamp17() == null ? 0 : this.getCamp17().hashCode() );
         return result;
   }   


}


