package com.laticobsa.modelo;
// Generated 22-jul-2017 13:48:47 by Hibernate Tools 4.3.1



/**
 * VwConsultaCartera generated by hbm2java
 */
public class VwConsultaCartera  implements java.io.Serializable {


     private VwConsultaCarteraId id;

    public VwConsultaCartera() {
    }

    public VwConsultaCartera(VwConsultaCarteraId id) {
       this.id = id;
    }
   
    public VwConsultaCarteraId getId() {
        return this.id;
    }
    
    public void setId(VwConsultaCarteraId id) {
        this.id = id;
    }




}


